### ISSUE TITLE
Consider fixing libstdc++ Linking Issue on macOS

### ISSUE THREAD

**Issue by amachang** [ThatNerdUKnow/libvmaf-sys#4]
Hi, I've discovered libvmaf-sys and am eager to utilize this library.

However, I encountered an issue when attempting to link to libstdc++ during the build process on macOS. Specifically, the problem arises from the following code in the build.rs file, which is incompatible with macOS:

```rust
println!("cargo:rustc-flags=-l dylib=stdc++");
```

This issue stems from the fact that, starting with version 10.9 (Mavericks), macOS adopted libc++ as the standard C++ library, replacing libstdc++.

I have crafted a fix to address this issue and committed it to my fork. You can review the specific changes at the following commit:
https://github.com/amachang/libvmaf-sys/commit/21c27bc5a571d9f8c15f3694defbe66dc75484ed

May I submit a pull request for this change? I would appreciate any feedback on this issue and the proposed fix. Thank you for your time and consideration.

**Comment by ThatNerdUKnow** [comment]
> May I submit a pull request for this change?

Please Do!

Do note that I recently made some changes to the build script for this library to support windows builds. ~~The important change I guess is that building libvmaf from source is no longer the default behavior in the build script, but it's still available by enabling the `build` feature. Otherwise you'll have to use your package manager to install libvmaf~~. For the sake of documentation being available on docs.rs i've changed the `build` feature to again be a default feature

**Comment by ThatNerdUKnow** [comment]
Resolved in release 0.4.3 of libvmaf-sys
